apiVersion: v1
kind: Secret
metadata:
  name: castbox-cb-bj-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
#---
#apiVersion: couchbase.com/v2
#kind: CouchbaseBucket
#metadata:
#  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: castbox-cb-bj
spec:
  image: couchbase/server:enterprise-7.1.4
  security:
    adminSecret: castbox-cb-bj-auth
  buckets:
    managed: false
  cluster:
#    analyticsServiceMemoryQuota: 1Gi
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 30
      timeWindow:
        abortCompactionOutsideWindow: false
      tombstonePurgeInterval: 72h0m0s
      viewFragmentationThreshold:
        percent: 30
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssuesTimePeriod: 2m0s
    autoFailoverTimeout: 2m0s
    dataServiceMemoryQuota: 2Gi
#    eventingServiceMemoryQuota: 256Mi
    indexServiceMemoryQuota: 2Gi
    indexStorageSetting: memory_optimized
#    searchServiceMemoryQuota: 256Mi
  networking:
    tls:
      rootCAs:
      - couchbase-server-ca
      secretSource:
        serverSecretName: couchbase-server-tls
        clientSecretName: couchbase-operator-tls
    dns:
      domain: couchbase.fungame.cloud
    exposeAdminConsole: true 
    adminConsoleServiceTemplate:
      spec:
        type: LoadBalancer
    exposedFeatures: 
#      - xdcr
      - client
    exposedFeatureServiceTemplate:
      spec:
        type: LoadBalancer
  servers:
  - name: bj-local-data-index-query
    size: 1
    services:
    - data
    - index
    - query
    volumeMounts:
      default: couchbase
#  - size: 2
#    name: index_services
#    services:
#    - index
#    volumeMounts:
#      default: couchbase
#  - size: 1
#    name: query_services
#    services:
#    - query
#    - search
#    - eventing
#    - analytics
#    volumeMounts:
#      default: couchbase
  enableOnlineVolumeExpansion: true
  volumeClaimTemplates: 
  - metadata:
      name: couchbase
    spec:
      storageClassName: local-path 
      resources: 
        requests:
          storage: 1Gi
