---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-path
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  pvDir: /opt/local-path-provisioner
volumeBindingMode: WaitForFirstConsumer
